language: java
cache:
  directories:
  - $HOME/.m2

services:
  - mysql  

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS pine;'

jdk:
  - oraclejdk11

script:
  - MYSQL_USER=travis MYSQL_PASSWORD= ./mvnw flyway:migrate
  - MYSQL_USER=travis MYSQL_PASSWORD= ./mvnw test
